- name: play level variables
  hosts: local
  connection: local
  vars_file:
    Course.yaml
  tasks:
  - name: Printing variables
    vars:
      COURSE: "Ansible"
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"