- name: variable perfernce
  hosts: local
  connection: local
  vars:
    NAME: "Ansible from play"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter username
  tasks:
  - name: print variables
    vars:
      NAME: ANsible from Task level
      ansible.builtin.debug:
        msg: "print {{ NAME }}"
