- name: variable perfernce
  hosts: local
  connection: local
  vars:
    NAME: "Ansible from play"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter username
    private: false
  tasks:
  - name: print variables
    # vars:
    #   NAME: ANsible from Task level
    ansible.builtin.debug:
        msg: "print {{ NAME }}"


# 1. Args
# 2. Task
# 3. File
# 4. Prompt
# 5. Play
# 6. Inventory