- name: install packages
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop: # list of string
    - mysql
    - zip
    - nginx